package logica;

public enum Especialidad {
    ODONTOLOGIA_GENERAL,
    CIRUGIA_ORAL_Y_MAXILOFACIAL,
    ENDODONCIA,
    ODONTOLOGIA_ESTETICA,
    ODONTOPEDIATRIA,
    ORTODONCIA,
    PATOLOGIA_BUCAL,
    PERIODONCIA,
    PROSTODONCIA_Y_REHABILITACION_ORAL,
    RADIOLOGIA_ORAL_Y_MAXILOFACIAL;
}
